-- Create Table
CREATE TABLE CONTRACT (ID BIGINT NOT NULL, ARCHIVEDURATION INTEGER, DESCRIPTION VARCHAR(255), ENDDATE DATE, FEDERALSTATE VARCHAR(255), FREQUENCY VARCHAR(255), HOURSPERWEEK FLOAT, STARTDATE DATE, STATUS VARCHAR(255), TERMINATIONDATE DATE, EMPLOYEE_ID BIGINT, SUPERVISOR_ID BIGINT, PRIMARY KEY (ID));
CREATE TABLE PERSON (ID BIGINT NOT NULL, DATEOFBIRTH DATE, EMAILADDRESS VARCHAR(255), FIRSTNAME VARCHAR(255), LASTNAME VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE ROLE (ID BIGINT NOT NULL, NAME VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE TIMESHEET (ID BIGINT NOT NULL, DESCRIPTION VARCHAR(255), ENDDATE DATE, SIGNEDBYEMPLOYEE DATE, SIGNEDBYSUPERVISOR DATE, STARTDATE DATE, TIMESHEETSTATUS VARCHAR(255), TYPE VARCHAR(255), CONTRACT_ID BIGINT, PRIMARY KEY (ID));
CREATE TABLE WORKREPORT (ID BIGINT NOT NULL, DAY DATE, DESCRIPTION VARCHAR(255), ENDTIME TIME, STARTTIME TIME, TYPE VARCHAR(255), TIMESHEET_ID BIGINT, PRIMARY KEY (ID));
CREATE TABLE PERSONCONFIG (ID BIGINT NOT NULL, IDENTIFIER VARCHAR(255), VALUE VARCHAR(4096), PERSON_ID BIGINT, PRIMARY KEY (ID));
CREATE TABLE CONTRACT_DELEGATE (contract_id BIGINT NOT NULL, delegate_id BIGINT NOT NULL, PRIMARY KEY (contract_id, delegate_id));
CREATE TABLE CONTRACT_SECRETARY (contract_id BIGINT NOT NULL, secretary_id BIGINT NOT NULL, PRIMARY KEY (contract_id, secretary_id));
CREATE TABLE CONTRACT_TIMESHEET (Contract_ID BIGINT NOT NULL, timeSheets_ID BIGINT NOT NULL, PRIMARY KEY (Contract_ID, timeSheets_ID));
CREATE TABLE person_role (person_id BIGINT NOT NULL, role_id BIGINT NOT NULL, PRIMARY KEY (person_id, role_id));
CREATE TABLE REMINDER (ID BIGINT NOT NULL, PERSON_ID BIGINT, TIMESHEET_ID BIGINT, PRIMARY KEY (ID))

-- Create Constraints
ALTER TABLE CONTRACT ADD CONSTRAINT CONTRACTEMPLOYEEID FOREIGN KEY (EMPLOYEE_ID) REFERENCES PERSON (ID);
ALTER TABLE CONTRACT ADD CONSTRAINT CNTRACTSPERVISORID FOREIGN KEY (SUPERVISOR_ID) REFERENCES PERSON (ID);
ALTER TABLE TIMESHEET ADD CONSTRAINT TMESHEETCONTRACTID FOREIGN KEY (CONTRACT_ID) REFERENCES CONTRACT (ID);
ALTER TABLE WORKREPORT ADD CONSTRAINT WRKREPORTTMSHEETID FOREIGN KEY (TIMESHEET_ID) REFERENCES TIMESHEET (ID);
ALTER TABLE PERSONCONFIG ADD CONSTRAINT PRSONCONFIGPRSONID FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID);
ALTER TABLE REMINDER ADD CONSTRAINT REMINDER_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID)
ALTER TABLE REMINDER ADD CONSTRAINT RMINDERTIMESHEETID FOREIGN KEY (TIMESHEET_ID) REFERENCES TIMESHEET (ID)

-- Create Sequence Table
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(15), PRIMARY KEY (SEQ_NAME));
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0);
