INSERT INTO ROLE (ID, NAME) VALUES (1, 'ADMINISTRATOR');
INSERT INTO ROLE (ID, NAME) VALUES (2, 'DELEGATE');
INSERT INTO ROLE (ID, NAME) VALUES (3, 'EMPLOYEE');
INSERT INTO ROLE (ID, NAME) VALUES (4, 'SECRETARY');
INSERT INTO ROLE (ID, NAME) VALUES (5, 'SUPERVISOR');
INSERT INTO ROLE (ID, NAME) VALUES (6, 'GUEST');