INSERT INTO PERSON (ID, DATEOFBIRTH, EMAILADDRESS, FIRSTNAME, LASTNAME) VALUES (3, '1995-06-21', 'peter@lustig.de', 'Peter', 'Lustig');
INSERT INTO PERSON (ID, DATEOFBIRTH, EMAILADDRESS, FIRSTNAME, LASTNAME) VALUES (4, '1990-01-01', 'max@mustermann.de', 'Max', 'Muster');
INSERT INTO PERSON (ID, DATEOFBIRTH, EMAILADDRESS, FIRSTNAME, LASTNAME) VALUES (5, '1990-01-01', 'martin@mustermann.de', 'Martin', 'Mustermann');
INSERT INTO CONTRACT(ID, ARCHIVEDURATION, DESCRIPTION, STATUS, STARTDATE, ENDDATE, TERMINATIONDATE, HOURSPERWEEK, EMPLOYEE_ID, SUPERVISOR_ID,FREQUENCY) VALUES (1, 24, 'TEST', 'PREPARED', '2018-01-01', '2020-01-01', '2022-01-01' ,20.0, 2, 3,'WEEKLY');
INSERT INTO CONTRACT_DELEGATE(CONTRACT_ID, DELEGATE_ID) VALUES (1, 4);
INSERT INTO CONTRACT_SECRETARY(CONTRACT_ID, SECRETARY_ID) VALUES (1, 5);
INSERT INTO PERSON_ROLE (PERSON_ID, ROLE_ID) VALUES (4, 2);
INSERT INTO PERSON_ROLE (PERSON_ID, ROLE_ID) VALUES (5, 4);
INSERT INTO PERSON_ROLE (PERSON_ID, ROLE_ID) VALUES (3, 5);
